version: '3.8'
services:
  azure-custom-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azure-agent
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - stack.env
# networks:
  # default:
    # external: true
    # name: kroo-dev
